# Generated by Django 5.0 on 2026-05-25 04:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('routines', '0001_initial'),
        ('users', '0002_userprofile_personal_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('completed', models.BooleanField(default=False)),
                ('day_note', models.TextField(blank=True)),
                ('exercises_done', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('routine_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='routines.routineday')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='users.userprofile')),
            ],
            options={
                'ordering': ('-date', '-created_at'),
            },
        ),
        migrations.AddConstraint(
            model_name='dailylog',
            constraint=models.UniqueConstraint(fields=('user', 'routine_day', 'date'), name='unique_daily_log_per_user_day_date'),
        ),
    ]
