# Generated by Django 5.0 on 2026-06-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhealthdata',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
