# Generated by Django 5.0 on 2026-07-02 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_add_soft_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='days_per_week',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='experience_level',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='intensity_preference',
            field=models.CharField(blank=True, choices=[('always_failure', 'Always to failure'), ('near_failure', 'Near failure'), ('comfortable', 'Comfortable')], max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='medical_conditions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='priority_muscles',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='session_duration_minutes',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='training_style',
            field=models.CharField(blank=True, choices=[('strength', 'Strength'), ('hypertrophy', 'Hypertrophy'), ('endurance', 'Endurance'), ('power', 'Power'), ('general', 'General')], max_length=20),
        ),
    ]
