# Generated by Django 5.0 on 2026-05-24 22:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_userprofile_personal_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutineDay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_number', models.PositiveSmallIntegerField()),
                ('day_name', models.CharField(max_length=40)),
                ('is_rest_day', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('day_number',),
            },
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('gemini_prompt_hash', models.CharField(blank=True, max_length=128)),
                ('raw_gemini_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routines', to='users.userprofile')),
            ],
            options={
                'ordering': ('-year', '-month', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='RoutineExercise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('muscle_group', models.CharField(blank=True, max_length=80)),
                ('sets', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('reps', models.CharField(blank=True, max_length=40)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('rest_seconds', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True)),
                ('video_url', models.URLField(blank=True)),
                ('variants', models.JSONField(blank=True, default=list)),
                ('instructions', models.TextField(blank=True)),
                ('search_term', models.CharField(blank=True, max_length=120)),
                ('order', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='routines.routineday')),
            ],
            options={
                'ordering': ('order', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='RoutineWeek',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('week_number', models.PositiveSmallIntegerField()),
                ('focus', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='routines.routine')),
            ],
            options={
                'ordering': ('week_number',),
            },
        ),
        migrations.AddField(
            model_name='routineday',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='routines.routineweek'),
        ),
        migrations.AddConstraint(
            model_name='routine',
            constraint=models.UniqueConstraint(fields=('user', 'month', 'year'), name='unique_routine_per_user_month_year'),
        ),
        migrations.AddConstraint(
            model_name='routine',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user',), name='unique_active_routine_per_user'),
        ),
        migrations.AddConstraint(
            model_name='routine',
            constraint=models.CheckConstraint(check=models.Q(('month__gte', 1), ('month__lte', 12)), name='routine_month_between_1_and_12'),
        ),
        migrations.AddConstraint(
            model_name='routineexercise',
            constraint=models.UniqueConstraint(fields=('day', 'order'), name='unique_exercise_order_per_day'),
        ),
        migrations.AddConstraint(
            model_name='routineweek',
            constraint=models.UniqueConstraint(fields=('routine', 'week_number'), name='unique_week_per_routine'),
        ),
        migrations.AddConstraint(
            model_name='routineweek',
            constraint=models.CheckConstraint(check=models.Q(('week_number__gte', 1), ('week_number__lte', 4)), name='routine_week_between_1_and_4'),
        ),
        migrations.AddConstraint(
            model_name='routineday',
            constraint=models.UniqueConstraint(fields=('week', 'day_number'), name='unique_day_per_week'),
        ),
        migrations.AddConstraint(
            model_name='routineday',
            constraint=models.CheckConstraint(check=models.Q(('day_number__gte', 1), ('day_number__lte', 7)), name='routine_day_between_1_and_7'),
        ),
    ]
