# Generated by Django 5.0 on 2026-06-13 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoredExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('force', models.CharField(blank=True, default='', max_length=50)),
                ('level', models.CharField(blank=True, default='', max_length=50)),
                ('mechanic', models.CharField(blank=True, default='', max_length=50)),
                ('equipment', models.CharField(blank=True, default='', max_length=100)),
                ('primary_muscles', models.JSONField(blank=True, default=list)),
                ('secondary_muscles', models.JSONField(blank=True, default=list)),
                ('instructions', models.TextField(blank=True, default='')),
                ('category', models.CharField(blank=True, default='', max_length=50)),
                ('image_paths', models.JSONField(blank=True, default=list)),
                ('external_id', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Stored Exercise',
                'verbose_name_plural': 'Stored Exercises',
                'ordering': ('name',),
            },
        ),
    ]
