# Generated by Django 5.0 on 2026-09-10 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0004_add_soft_delete'),
        ('users', '0004_userprofile_days_per_week_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='routine',
            name='unique_routine_per_user_month_year',
        ),
        migrations.RemoveConstraint(
            model_name='routine',
            name='routine_month_between_1_and_12',
        ),
        migrations.AddField(
            model_name='routine',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('ai_generated', 'AI Generated')], db_index=True, default='ai_generated', max_length=20),
        ),
        migrations.AddField(
            model_name='routineexercise',
            name='source_external_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='storedexercise',
            name='image_license_note',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='storedexercise',
            name='image_provider',
            field=models.CharField(blank=True, default='free-exercise-db', max_length=30),
        ),
        migrations.AlterField(
            model_name='routine',
            name='month',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='routine',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='routine',
            constraint=models.UniqueConstraint(condition=models.Q(('source', 'ai_generated')), fields=('user', 'month', 'year'), name='unique_ai_routine_per_user_month_year'),
        ),
        migrations.AddConstraint(
            model_name='routine',
            constraint=models.CheckConstraint(check=models.Q(('month__isnull', True), models.Q(('month__gte', 1), ('month__lte', 12)), _connector='OR'), name='routine_month_between_1_and_12'),
        ),
    ]
