# Generated by Django 5.0 on 2026-09-15 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0005_routine_source_and_manual_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedexercise',
            name='gif_path',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
