# Generated by Django 5.0 on 2026-09-20 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0006_backfill_source_external_id'),
        ('routines', '0007_import_exercises_v2'),
    ]

    operations = [
    ]
