# Generated by Django 5.0 on 2026-09-20 01:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0008_merge_20260919_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='cycle_started_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='RoutineEditProposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=10)),
                ('target_month', models.PositiveSmallIntegerField()),
                ('target_year', models.PositiveSmallIntegerField()),
                ('summary', models.TextField(blank=True)),
                ('changes', models.JSONField(default=list)),
                ('raw_gemini_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='routines.routine')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='routineeditproposal',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('routine',), name='unique_pending_proposal_per_routine'),
        ),
    ]
